---

project_name: assmble

release:
  disable: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    # id: user
    binary: user
    main: ./cmd/user
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      # - darwin

    goarch:
      - amd64
      # - arm
      # - arm64

archives:
- format: binary

blobs:
  - provider: s3
    region: eu-central-1
    disableSSL: false
    bucket: goreleaser-bucket
    folder: '{{ .ProjectName }}/{{ .Tag }}'

checksum:
  name_template: 'checksums.txt'
